### ISSUE TITLE
Off by one

### ISSUE THREAD

**Issue by benheb** [substack/invoicer#12]
Dates appear to be off by one when exporting to PDF, with the dates showing the day prior to when they should. Doesn't look like a ton of activity in the repo lately, but is this any chance a quick fix you could make? 

<img width="631" alt="substack_invoicer__generate_pdf_invoices_from_json" src="https://cloud.githubusercontent.com/assets/910495/12991412/5d1c8694-d0cc-11e5-9528-eb903ce69622.png">

**Comment by andrezsanchez** [comment]
The fix for this, #17, was merged, so this can be closed.

**Comment by noffle** [comment]
Thanks for noticing @andrezsanchez
